import Link from "next/link";
import { isContactReady } from "@/lib/contact-settings";
import { createPageMetadata } from "@/lib/metadata";

export const metadata = createPageMetadata({
  title: "Datenschutz",
  description: "Datenschutzhinweise der APM-Praxis René Aufhauser in Salzburg.",
  canonical: "/datenschutz",
});
export default function DatenschutzPage() {
  return <main id="main" className="narrow section legal-copy">
    <h1>Datenschutz</h1><p>Diese Hinweise erläutern die Verarbeitung personenbezogener Daten beim Besuch dieser Website und bei Kontaktanfragen. Stand: September 2026.</p>
    <h2>Verantwortlicher</h2><p>René Aufhauser, Tauxgasse 24A, 5020 Salzburg, Österreich.<br />E-Mail: <a href="mailto:apm.aufhauser@gmail.com">apm.aufhauser@gmail.com</a><br />Telefon: <a href="tel:+436641632076">+43 664 1632076</a></p>
    <h2>Bereitstellung der Website</h2><p>Die Website wird über Vercel bereitgestellt. Beim Aufruf werden technisch erforderliche Verbindungsdaten verarbeitet, insbesondere die IP-Adresse, der Zeitpunkt, die angeforderte Ressource und Informationen zum Browser. Dies dient der Auslieferung und Sicherheit der Website. Rechtsgrundlage ist unser berechtigtes Interesse an einem sicheren und funktionsfähigen Webauftritt gemäß Art. 6 Abs. 1 lit. f DSGVO.</p><p>Informationen zum Anbieter und zur Verarbeitung durch Vercel finden Sie in der <a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noreferrer">Datenschutzerklärung von Vercel</a>. Bei der Nutzung internationaler Infrastrukturen kann eine Verarbeitung außerhalb des EWR stattfinden.</p>
    <h2>Kontakt per E-Mail und Telefon</h2><p>Wir verarbeiten Ihre Kontaktdaten und die mitgeteilten Informationen, um Ihre Anfrage zu beantworten und Termine zu vereinbaren. Bei vorvertraglichen oder vertraglichen Anfragen erfolgt dies auf Grundlage von Art. 6 Abs. 1 lit. b DSGVO, bei sonstigen Anfragen auf Grundlage unseres berechtigten Interesses an der Beantwortung gemäß Art. 6 Abs. 1 lit. f DSGVO.</p><p>Das E-Mail-Postfach wird über Gmail von Google bereitgestellt. Bitte beschränken Sie Ihre Angaben auf das für die Terminvereinbarung Erforderliche und senden Sie keine Diagnosen, Befunde oder sonstigen Gesundheitsunterlagen. <a href="https://policies.google.com/privacy" target="_blank" rel="noreferrer">Informationen zum Datenschutz bei Google</a>.</p>
    {isContactReady() && <><h2>Kontaktformular</h2><p>Ihre Angaben werden über Resend an das Praxispostfach übermittelt. Die Website führt dafür keine eigene Nachrichtendatenbank. Beim Versand können technische Verarbeitungs- und Zustelldaten beim Dienstleister entstehen. Die Verarbeitung dient denselben Zwecken und Rechtsgrundlagen wie direkte Kontaktanfragen.</p><p>Zur Begrenzung missbräuchlicher Anfragen werden bei Upstash zeitlich begrenzte Zähler mit einer pseudonymisierten, mit einem geheimen Schlüssel berechneten Prüfsumme der IP-Adresse gespeichert. Die Zähler werden nach spätestens 24 Stunden gelöscht. Grundlage ist das berechtigte Interesse am Schutz vor Missbrauch. <a href="https://resend.com/legal/privacy-policy" target="_blank" rel="noreferrer">Resend-Datenschutz</a> und <a href="https://upstash.com/trust/privacy.pdf" target="_blank" rel="noreferrer">Upstash-Datenschutz</a>.</p></>}
    <h2>Speicherdauer</h2><p>Kontaktdaten und Korrespondenz werden so lange benötigt, wie die Bearbeitung der Anfrage, die Abwicklung eines Vertrags oder die Wahrung gesetzlicher Aufbewahrungs- und Nachweispflichten dies erfordern. Die konkrete Dauer richtet sich nach Zweck und Inhalt der Korrespondenz. Technische Daten werden nur so lange verarbeitet, wie sie für Betrieb, Sicherheit oder Fehleranalyse erforderlich sind.</p>
    <h2 id="google-maps">Google Maps</h2><p>Auf der Kontaktseite können Sie eine Karte von Google Maps laden. Vor Ihrer Einwilligung wird kein Karteninhalt von Google angefordert. Wenn Sie „Google Maps zustimmen und laden“ wählen, stellt Ihr Browser eine Verbindung zu Google her. Dabei können unter anderem Ihre IP-Adresse, Browserinformationen und gegebenenfalls Kennungen an Google übermittelt werden. Eine Verarbeitung in den USA ist möglich.</p><p>Rechtsgrundlage ist Ihre Einwilligung gemäß Art. 6 Abs. 1 lit. a DSGVO sowie, soweit Informationen auf Ihrem Endgerät gespeichert oder ausgelesen werden, § 165 Abs. 3 TKG 2021. Sie können die Karte über die Schaltfläche unter der Karte wieder ausblenden. Dies verhindert weitere Einbettung durch diese Seite; bereits übermittelte Daten werden dadurch nicht zurückgerufen. Die Zustimmung gilt nur für die aktuell geöffnete Kartendarstellung.</p><p>Ohne eingebettete Karte können Sie die Adresse lesen oder einen normalen Routenlink öffnen. Beim Öffnen dieses Links verlassen Sie unsere Website. Es gelten die <a href="https://policies.google.com/privacy" target="_blank" rel="noreferrer">Datenschutzhinweise von Google</a>.</p>
    <h2>Schriftarten und Analysedienste</h2><p>Schriftarten werden mit der Website ausgeliefert, ohne beim Besuch Google Fonts zu kontaktieren. Es werden keine Einstellungen für die Darstellung gespeichert und keine Analyse- oder Werbedienste eingebunden.</p>
    <h2>Ihre Rechte</h2><p>Sie haben nach Maßgabe der DSGVO Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung und Datenübertragbarkeit. Einer Verarbeitung aufgrund berechtigter Interessen können Sie aus Gründen Ihrer besonderen Situation widersprechen. Erteilte Einwilligungen können Sie mit Wirkung für die Zukunft widerrufen.</p><p>Für die Ausübung Ihrer Rechte kontaktieren Sie uns bitte unter der oben genannten E-Mail-Adresse. Sie können sich außerdem bei der <a href="https://www.dsb.gv.at/" target="_blank" rel="noreferrer">österreichischen Datenschutzbehörde</a> beschweren.</p>
    <p><Link href="/impressum">Zum Impressum</Link></p>
  </main>;
}
